### PR TITLE
A-Shot (Week 1 & 2)

### PR DESCRIPTION
**Pull request by ATMI**
Finished report for the 1st week!

### CODE REVIEW

**Comment by ATMI** [comment]
The second week almost finished and some pull requests have already been merged, but ours haven't. Any issues with it?

**Comment by ATMI** [comment]
Added the 2nd week report

**Review by KelDakroury — APPROVED** [review]
{{< hint danger >}}
Feedback

Value Proposition:

Defining the Vision for Your Project:


Overall:
- Nice work!

Grade:
- Project Focus & Approach - 2
- Results & Analysis - 2
- Conclusions & Next Steps - 1
- Challenges & Solutions - 1 
- Progress Review Session with TA - 2 
- Communication & Presentation - 2
- Total: 10/10

{{< /hint >}}

**Comment by KelDakroury** [comment]
A-shot week1 report:

{{< hint danger >}}
Feedback

Overall:
- Nice work!

Grade:
- Project Focus & Approach - 2
- Results & Analysis - 2
- Conclusions & Next Steps - 1
- Challenges & Solutions - 1
- Progress Review Session with TA - 2 (Not applicable for week 1)
- Communication & Presentation - 2

- Total: 10/10
{{< /hint >}}

**Pull request merged**
