### PR TITLE
roomreco (Week 6): update link to Google Slides

### PR DESCRIPTION
**Pull request by machnevegor**

### CODE REVIEW

**Comment by markovav-official** [comment]
Please, upload your presentation as PDF

**Comment by machnevegor** [comment]
> Please, upload your presentation as PDF

We can convert the presentation to PDF, but in that case the demo videos will not be saved :(

**Comment by IU-PR** [comment]
you can embed your video as well. Please add PDF and a video

**Comment by machnevegor** [comment]
> you can embed your video as well. Please add PDF and a video

Done

**Review by markovav-official — APPROVED** [review]

**Pull request merged**
